#pragma once

#include <algorithm>
#include <any>
#include <array>
#include <cmath>
#include <concepts>
#include <filesystem>
#include <flat_map>
#include <flat_set>
#include <format>
#include <functional>
#include <iosfwd>
#include <iostream>
#include <memory>
#include <numbers>
#include <optional>
#include <random>
#include <ranges>
#include <set>
#include <span>
#include <string>
#include <string_view>
#include <typeindex>
#include <unordered_map>
#include <utility>
#include <vector>